test_string = 'WEILMPGVCTNAQYVGWKEHYLKSLGFMGCLKLKEHDQLLAGGMTDRKDHPEEVYFFYVEWQKCQSVPPAQYIASDSPPVSIDVHKVMNMCTVAEDTCHKKCDIPQAWDVRKIGLRYTHWMESNYNSIGHFRHMFPPSMEQVIRSEHFMFLPWSFMKDTHCKCKRTIHWHTGQIMMFCMVSGTKWMEHKKNSTRTGDFPAFQPCRFKQQVRMTKTVKTMGQHDMFEPKWLLAFYNLHEWGVYKHIDWKLAIFIEMKHDSEDISSTIQWETWIPRVRYQVGYEEKRKEHMFDNMTEDWCNVGRMHAWKMEIQVGGSPGDTVHMAAASHNANYEWYKTVCIQDQTTWSVSHARDKFASVDAPRFSSVRYIQGISDNEINESQTAMNSIMDMAPFFWDVYTLKEFGDAKWKIYGTQFQAKTWMGKSRISMCSDTQRIFSHHNMKNGMSSESHAEKTGQDGLRARAYRVHLIHEFGREYGKWQYDLDFWNRYLVAKVTEFASIVHMGCRKGHKEQDVTEMDDLAKLGYDECKRSGGLRAGGAHEWANGTMESELCNIDSGKVPTCFPRRVARLMERISPKCIVNAKGDGTRPGCQLMFDKTGRWWGGWWDYFGAHYVWFPTQCHMCISIKPACTDFKYPWMTNYPELLKYSKYHGFPQVCGYILFLHECTQEPAILNSIQKRFHNWMMQMEYCVCFYKPAYRQHMLNLMETCSIIVKFPERDEVMTDKCTTCPVPYYVQSAIQDLLRLLFKQNYHMEFAMWGCPWEHGALLNPQTRMKSCHKIWRWQRVDRCKVCRVITCDLLGMNIQLLIGGFRICRDQGSRLAWPHMYQHWHVNISTRNSNSLQKLERWNMCILTHKEKKMDCPAKRGLIGHRWHTRCHHAISWNENPGMSGPNDCGFIHLAMPSQSMWFVCVSFCGAEIDSGYLRMWNWFMFNCHSFACI'

mass_table = {'A':  71.03711,
                'C':   103.00919,
                'D':   115.02694,
                'E':   129.04259,
                'F':   147.06841,
                'G':   57.02146,
                'H':   137.05891,
                'I':   113.08406,
                'K':   128.09496,
                'L':   113.08406,
                'M':   131.04049,
                'N':   114.04293,
                'P':   97.05276,
                'Q':   128.05858,
                'R':   156.10111,
                'S':   87.03203,
                'T':   101.04768,
                'V':   99.06841,
                'W':   186.07931,
                'Y':   163.06333}

def translate(data):
    total_sum = 0
    for letter in data:
        if letter in mass_table:
            #print(mass_table)
            total_sum += mass_table[letter]
        else:
            print(letter)
    return total_sum

print(translate(test_string))

#quicker solution!
#total_sum
#for letter in test_string:
#    total_sum += mass_table[letter]
#print(total_sum)